### PR TITLE
Async methods

### PR DESCRIPTION
**Pull request by arnaldopereira**
- Updated travis configuration
- Created requirements files
- Created Makefile to use nosetests with coverage
- Removed test with mock requests and responses -- which we'll eventually add back
- And, of course, changes to these methods to make them async: authorize, refund, void, capture, get_transaction_data, get_order_data, get_customer_data
- The above mentioned methods are now all class-based
- Docstrings of braspag/core.py updated
- Moved the mock data files to tests/data-unused, I think it's good to keep them in the tree so that we might reuse them if we can add mocked tests back in the near future

### CODE REVIEW

**Comment by arnaldopereira** [comment]
repositório errado.

**Comment by seocam** [comment]
@arnaldopereira-luizalabs Se tiverem atualizacoes para a lib estamos aceitando pull requests ;)

**Comment by arnaldopereira** [comment]
@seocam temos várias, mas ainda estamos alterando ela constantemente. Quando fecharmos um release candidate eu mando os pull requests. valeu!

**Comment by seocam** [comment]
Valeu @arnaldopereira-luizalabs!

**Pull request closed without merging**
